spring:
  application:
    name: camundaDemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_2020?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=Hongkong
    username: root
    password: as123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池中允许的最大连接数，缺省值10
      maximum-pool-size: 50
      minimum-idle: 8
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
server:
  port: 8000
camunda:
  bpm:
    admin-user:
      id: admin
      password: as123456
      first-name: cj
    filter:
      create: All tasks
